// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication10.DataAccessLayer;

#nullable disable

namespace WebApplication10.Migrations
{
    [DbContext(typeof(SearchContext))]
    [Migration("20230724235346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuerySearchResult", b =>
                {
                    b.Property<int>("QueriesId")
                        .HasColumnType("int")
                        .HasColumnName("queries_id");

                    b.Property<int>("ResultsId")
                        .HasColumnType("int")
                        .HasColumnName("results_id");

                    b.HasKey("QueriesId", "ResultsId")
                        .HasName("pk_query_search_result");

                    b.HasIndex("ResultsId")
                        .HasDatabaseName("ix_query_search_result_results_id");

                    b.ToTable("query_search_result", (string)null);
                });

            modelBuilder.Entity("WebApplication10.DataAccessLayer.Models.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QueryKeywordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("query_keyword_hash");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.ToTable("queries", (string)null);
                });

            modelBuilder.Entity("WebApplication10.DataAccessLayer.Models.SearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snippet");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("QuerySearchResult", b =>
                {
                    b.HasOne("WebApplication10.DataAccessLayer.Models.Query", null)
                        .WithMany()
                        .HasForeignKey("QueriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_search_result_queries_queries_id");

                    b.HasOne("WebApplication10.DataAccessLayer.Models.SearchResult", null)
                        .WithMany()
                        .HasForeignKey("ResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_search_result_results_results_id");
                });
#pragma warning restore 612, 618
        }
    }
}
